### ISSUE TITLE
cocoscreator使用typescript時，單元測試遇到的問題

### ISSUE THREAD

**Issue by Tweety817** [mangogan-git/jest_totuiral#1]
您好，使用jest測試cocoscreator內的各個typescript腳本。cmd都會跳錯，錯誤如下：
Test suite failed to run

    TypeError: Cannot read property 'ccclass' of undefined

      2 | import {cc} from '../../../creator.d';
      3 | import {cc_decorator} from '../../../creator.d';
    > 4 | const {ccclass, property} = cc_decorator;

解很久不知道該如何處理。看您的js腳本是有cc.class也可以通過測試的。
想請教該如何是好？
感謝您！

**Comment by mangogan-git** [comment]
@Tweety817 
我沒有直接使用過 typescript ，這邊僅僅是猜測原因。

範例中的 jest 沒有安裝 ts 的 plugin, 所以在遇到 ts 會產生錯誤

另外在 cocos 在 preview 或 build 時可能還有對 source code做其它的處理
這些處理變成你可能要自己實做

以我的範例來說， 在撰寫 cc.Class 並不用添加 module.exports 來暴露 module
因為 cocos 會在編譯時自動幫你添加
但 jest 並不知道這段工作，造成在 import component 時發生錯誤
所以我自己寫了一個 [babel-plugin](https://github.com/mangogan-git/jest_totuiral/blob/master/cocos_creator/babel_plugin/babel-cc-class.js) 讓測試時可以運作

有空的話我再研究看看 ts 的版本

**Comment by pino2046** [comment]
请问现在有typescript版本的样例吗？

**Comment by mangogan-git** [comment]
hi, 我有更新 typescript 版本的範例了
安裝過程: https://slides.com/mangogan/jestxccc#/23/8
creator 專案: https://github.com/mangogan-git/jest_totuiral/tree/master/cocos_creator/ts
